import { GameModeDefinition } from "./types";
import { isModeEnabled } from "./flags";

export const GAME_MODES: GameModeDefinition[] = [
  // ==========================================
  // COMPETE FAMILY (Prestige & Competitive Integrity)
  // ==========================================
  {
    id: "mode_ranked_classic",
    slug: "ranked-classic",
    family: "compete",
    displayName: "Ranked Classic",
    shortTagline: "The World Standard",
    description: "Head-to-head live 1v1 duel. 8 identical questions, 10 seconds per round, server-authoritative ELO rating on the line.",
    ranked: true,
    questionCount: 8,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2-3 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "elo_k24",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: "classic",
    shareable: true,
    active: true,
    featureFlag: "mode_ranked_classic",
    badgeLabel: "ELO Ranked",
    iconName: "Swords",
    accentColor: "var(--gold)",
  },
  {
    id: "mode_ranked_blitz",
    slug: "ranked-blitz",
    family: "compete",
    displayName: "Ranked Blitz",
    shortTagline: "Pure Speed Duel",
    description: "High-intensity competitive speed format. 12 questions, 5 seconds per question. Tiebreaker derived from server response times.",
    ranked: true,
    questionCount: 12,
    timePerQuestionMs: 5000,
    totalTimeMs: null,
    estimatedDuration: "~60s",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "elo_k24",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: "blitz",
    shareable: true,
    active: true,
    featureFlag: "mode_ranked_blitz",
    badgeLabel: "Speed ELO",
    iconName: "Zap",
    accentColor: "oklch(0.85 0.18 200)",
  },
  {
    id: "mode_free_answer_ranked",
    slug: "free-answer-ranked",
    family: "compete",
    displayName: "Free Answer Arena",
    shortTagline: "No Multiple Choice",
    description: "Zero multiple choice. Type the answer directly. Deterministic evaluation with typo and alias support. The purest test of recall.",
    ranked: true,
    questionCount: 8,
    timePerQuestionMs: 7000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "free_text",
    eliminationRule: "none",
    scoringRule: "elo_k24",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: "free_answer",
    shareable: true,
    active: true,
    featureFlag: "mode_free_answer_ranked",
    badgeLabel: "Pure Recall",
    iconName: "Keyboard",
    accentColor: "oklch(0.88 0.21 122)",
  },
  {
    id: "mode_weekend_cup",
    slug: "weekend-cup",
    family: "compete",
    displayName: "Weekend Cup",
    shortTagline: "Weekly Championship",
    description: "Scheduled weekly tournament bracket. Compete through qualification, quarters, semi-finals, and the grand championship.",
    ranked: true,
    questionCount: 8,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "Multi-round",
    answerInputType: "mcq",
    eliminationRule: "bracket",
    scoringRule: "standard",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: false,
    officialLeaderboard: true,
    ratingPool: "classic",
    shareable: true,
    active: true,
    featureFlag: "mode_weekend_cup",
    badgeLabel: "Tournament",
    iconName: "Trophy",
    accentColor: "var(--gold)",
  },
  {
    id: "mode_qualifiers",
    slug: "qualifiers",
    family: "compete",
    displayName: "Championship Qualifiers",
    shortTagline: "Elite Access Gate",
    description: "Server-verified qualification gate for major competitive events. Requires Diamond+ rating or Top 10% Daily ranking.",
    ranked: true,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "hard",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_qualifiers",
    badgeLabel: "Diamond+",
    iconName: "ShieldCheck",
    accentColor: "oklch(0.8 0.15 215)",
  },
  {
    id: "mode_king_of_hill",
    slug: "king-of-the-hill",
    family: "compete",
    displayName: "King of the Hill",
    shortTagline: "100-Player Battle Royale",
    description: "100 competitors enter. Lowest performing 20% eliminated each round. Only the ultimate champion survives.",
    ranked: false,
    questionCount: 7,
    timePerQuestionMs: 7000,
    totalTimeMs: null,
    estimatedDuration: "~3 min",
    answerInputType: "mcq",
    eliminationRule: "bottom_percentile",
    scoringRule: "speed_streak_points",
    difficultyRule: "escalating",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_king_of_hill",
    badgeLabel: "Battle Royale",
    iconName: "Crown",
    accentColor: "oklch(0.83 0.16 84)",
  },
  {
    id: "mode_sudden_death",
    slug: "sudden-death",
    family: "compete",
    displayName: "Sudden Death",
    shortTagline: "One Error = Out",
    description: "High-stakes survival challenge. The first incorrect answer immediately ends your run. Outlast thousands of global competitors.",
    ranked: false,
    questionCount: null,
    timePerQuestionMs: 8000,
    totalTimeMs: null,
    estimatedDuration: "Survival",
    answerInputType: "mcq",
    eliminationRule: "one_strike",
    scoringRule: "streak_length",
    difficultyRule: "escalating",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_sudden_death",
    badgeLabel: "Survival",
    iconName: "Skull",
    accentColor: "oklch(0.66 0.26 5)",
  },
  {
    id: "mode_world_quiz",
    slug: "world-quiz",
    family: "compete",
    displayName: "World Quiz Championship",
    shortTagline: "Global Scheduled Event",
    description: "Scheduled international tournament where all countries clash simultaneously on synchronized rounds.",
    ranked: true,
    questionCount: 15,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~5 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "hard",
    categoryRule: "all",
    allowsRetry: false,
    officialLeaderboard: true,
    ratingPool: "classic",
    shareable: true,
    active: true,
    featureFlag: "mode_world_quiz",
    badgeLabel: "Global Event",
    iconName: "Globe",
    accentColor: "var(--primary)",
  },

  // ==========================================
  // QUICK FAMILY (Fast Replayable Formats & PBs)
  // ==========================================
  {
    id: "mode_blitz_5s",
    slug: "blitz",
    family: "quick",
    displayName: "5-Second Blitz",
    shortTagline: "Rapid Instinct Trivia",
    description: "5 seconds per question. 10 rapid-fire questions without pause. Instant feedback, personal best records, and daily speed rankings.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 5000,
    totalTimeMs: null,
    estimatedDuration: "~45s",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "speed_streak_points",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_blitz_5s",
    badgeLabel: "⚡ 5s per question",
    iconName: "Zap",
    accentColor: "oklch(0.85 0.18 200)",
  },
  {
    id: "mode_lightning_60",
    slug: "lightning",
    family: "quick",
    displayName: "60-Second Lightning",
    shortTagline: "60 Seconds on the Clock",
    description: "One master 60-second countdown. Chain as many correct answers as humanly possible before the buzzer expires.",
    ranked: false,
    questionCount: null,
    timePerQuestionMs: null,
    totalTimeMs: 60000,
    estimatedDuration: "60s",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "lightning_volume",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_lightning_60",
    badgeLabel: "⏱️ 60s Master Timer",
    iconName: "Flame",
    accentColor: "oklch(0.7 0.22 45)",
  },
  {
    id: "mode_perfect_10",
    slug: "perfect-10",
    family: "quick",
    displayName: "Perfect 10",
    shortTagline: "Perfection or Nothing",
    description: "Exactly 10 questions. The primary objective is 10/10 perfection. One missed question will haunt your record.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~1-2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "perfection_time",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_perfect_10",
    badgeLabel: "10/10 Goal",
    iconName: "Target",
    accentColor: "oklch(0.88 0.21 122)",
  },
  {
    id: "mode_streak",
    slug: "streak",
    family: "quick",
    displayName: "Streak Mode",
    shortTagline: "Don't Break the Chain",
    description: "How many questions can you answer in a row without a single mistake? One wrong answer ends your run immediately.",
    ranked: false,
    questionCount: null,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "Variable",
    answerInputType: "mcq",
    eliminationRule: "one_strike",
    scoringRule: "streak_length",
    difficultyRule: "escalating",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_streak",
    badgeLabel: "🔥 1 Strike",
    iconName: "Flame",
    accentColor: "oklch(0.66 0.26 5)",
  },
  {
    id: "mode_double_or_nothing",
    slug: "double-or-nothing",
    family: "quick",
    displayName: "Double or Nothing",
    shortTagline: "Bank or Risk It All",
    description: "Build a massive score. At each checkpoint, choose to BANK your points safely or DOUBLE with higher difficulty.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "double_or_nothing",
    difficultyRule: "escalating",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_double_or_nothing",
    badgeLabel: "Risk / Reward",
    iconName: "Coins",
    accentColor: "oklch(0.83 0.16 84)",
  },
  {
    id: "mode_ladder",
    slug: "ladder",
    family: "quick",
    displayName: "The Ladder",
    shortTagline: "10 Tiers of Knowledge",
    description: "Climb through 10 progressively grueling difficulty tiers. From Level 1 (Easy) to Level 10 (Legendary). Only 4.8% reach Level 8.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "one_strike",
    scoringRule: "ladder_stages",
    difficultyRule: "escalating",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_ladder",
    badgeLabel: "10 Stages",
    iconName: "TrendingUp",
    accentColor: "oklch(0.7 0.2 300)",
  },
  {
    id: "mode_daily_gem",
    slug: "daily-gem",
    family: "quick",
    displayName: "Daily Gem",
    shortTagline: "One Daily Master Question",
    description: "Exactly ONE prestigious high-difficulty question per day worldwide. One official shot. Track the global success rate and share your card.",
    ranked: false,
    questionCount: 1,
    timePerQuestionMs: 20000,
    totalTimeMs: null,
    estimatedDuration: "20s",
    answerInputType: "hybrid",
    eliminationRule: "none",
    scoringRule: "daily_gem",
    difficultyRule: "hard",
    categoryRule: "all",
    allowsRetry: false,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_daily_gem",
    badgeLabel: "💎 1 Q / Day",
    iconName: "Sparkles",
    accentColor: "oklch(0.85 0.15 150)",
  },
  {
    id: "mode_mystery",
    slug: "mystery",
    family: "quick",
    displayName: "Mystery Mode",
    shortTagline: "Unpredictable Variety",
    description: "Hidden categories and randomized difficulty. No pressure, no expectations—just spontaneous knowledge exploration.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "random_bounded",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_mystery",
    badgeLabel: "Surprise",
    iconName: "HelpCircle",
    accentColor: "oklch(0.75 0.15 280)",
  },

  // ==========================================
  // TRAIN FAMILY (Skill Mastery & Weakness Elimination)
  // ==========================================
  {
    id: "mode_infinite_training",
    slug: "training",
    family: "train",
    displayName: "Infinite Practice",
    shortTagline: "Zero Stress Training",
    description: "Endless questions, no timer pressure, free XP gain. Test concepts at your own pace without Elo consequences.",
    ranked: false,
    questionCount: null,
    timePerQuestionMs: null,
    totalTimeMs: null,
    estimatedDuration: "Free",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: false,
    active: true,
    featureFlag: "mode_infinite_training",
    badgeLabel: "No Timer",
    iconName: "Infinity",
    accentColor: "var(--primary)",
  },
  {
    id: "mode_adaptive_training",
    slug: "adaptive-training",
    family: "train",
    displayName: "Adaptive Training",
    shortTagline: "Personalized Progression",
    description: "The engine analyzes your personal category statistics, error history, and knowledge blind spots to build targeted drill sessions.",
    ranked: false,
    questionCount: 12,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "player_adaptive",
    categoryRule: "weakness",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: false,
    active: true,
    featureFlag: "mode_adaptive_training",
    badgeLabel: "Personalized",
    iconName: "BrainCircuit",
    accentColor: "oklch(0.8 0.15 215)",
  },
  {
    id: "mode_category_runs",
    slug: "category-runs",
    family: "train",
    displayName: "Category Sprints",
    shortTagline: "Domain Specialization",
    description: "Focus on a single domain—History, Geography, Science, Cinema, Art, or Literature. Master your preferred category.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "balanced",
    categoryRule: "single",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_category_runs",
    badgeLabel: "By Subject",
    iconName: "Layers",
    accentColor: "var(--accent)",
  },
  {
    id: "mode_category_tower",
    slug: "category-tower",
    family: "train",
    displayName: "Category Towers",
    shortTagline: "100 Floors of Mastery",
    description: "11 individual towers (History, Geography, Science, etc.). Climb floor by floor and face milestone Boss questions every 5 floors.",
    ranked: false,
    questionCount: 5,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~1 min / floor",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "tower_floors",
    difficultyRule: "escalating",
    categoryRule: "single",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_category_tower",
    badgeLabel: "Floor 1-100",
    iconName: "Building2",
    accentColor: "oklch(0.83 0.16 84)",
  },
  {
    id: "mode_weakness_run",
    slug: "weakness-run",
    family: "train",
    displayName: "Weakness Run",
    shortTagline: "Fix Your Blind Spots",
    description: "10-15 questions explicitly selected from your lowest accuracy domains and recently missed concepts.",
    ranked: false,
    questionCount: 12,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "player_adaptive",
    categoryRule: "weakness",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: false,
    active: true,
    featureFlag: "mode_weakness_run",
    badgeLabel: "Targeted Drill",
    iconName: "ShieldAlert",
    accentColor: "oklch(0.66 0.26 5)",
  },

  // ==========================================
  // SOCIAL FAMILY (Peer Battles, Rivalries, Leagues & Wars)
  // ==========================================
  {
    id: "mode_friend_battle",
    slug: "friend-battle",
    family: "social",
    displayName: "Friend Battles",
    shortTagline: "Custom 1v1 Challenge",
    description: "Create a shareable battle link with your chosen format (Classic, Blitz, Free Answer, Perfect 10). Play synchronously or async.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_friend_battle",
    badgeLabel: "Custom Format",
    iconName: "Users",
    accentColor: "var(--primary)",
  },
  {
    id: "mode_rivalries",
    slug: "rivalries",
    family: "social",
    displayName: "Rivalry Battles",
    shortTagline: "Head-to-Head Series",
    description: "Track head-to-head records against your closest peers. Settle the score and defend your winning streak.",
    ranked: false,
    questionCount: 10,
    timePerQuestionMs: 10000,
    totalTimeMs: null,
    estimatedDuration: "~2 min",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_rivalries",
    badgeLabel: "H2H Series",
    iconName: "Swords",
    accentColor: "oklch(0.66 0.26 5)",
  },
  {
    id: "mode_private_leagues",
    slug: "private-leagues",
    family: "social",
    displayName: "Private Leagues",
    shortTagline: "Friends & Office Cup",
    description: "Create private fantasy-style leagues. Compete across Season ELO, Daily 12 consistency, and Blitz speed records.",
    ranked: false,
    questionCount: null,
    timePerQuestionMs: null,
    totalTimeMs: null,
    estimatedDuration: "Season",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: false,
    ratingPool: null,
    shareable: true,
    active: true,
    featureFlag: "mode_private_leagues",
    badgeLabel: "Private Club",
    iconName: "Trophy",
    accentColor: "var(--gold)",
  },
  {
    id: "mode_country_wars",
    slug: "country-wars",
    family: "social",
    displayName: "Country Wars",
    shortTagline: "Defend Your Flag",
    description: "184 nations compete for intellectual supremacy. Every correct answer in Ranked or Blitz contributes to national Power ranking.",
    ranked: true,
    questionCount: null,
    timePerQuestionMs: null,
    totalTimeMs: null,
    estimatedDuration: "Continuous",
    answerInputType: "mcq",
    eliminationRule: "none",
    scoringRule: "standard",
    difficultyRule: "balanced",
    categoryRule: "all",
    allowsRetry: true,
    officialLeaderboard: true,
    ratingPool: "classic",
    shareable: true,
    active: true,
    featureFlag: "mode_country_wars",
    badgeLabel: "National Rank",
    iconName: "Flag",
    accentColor: "var(--primary)",
  },
];

export function getModeBySlug(slug: string): GameModeDefinition | undefined {
  return GAME_MODES.find((m) => m.slug === slug || m.id === slug);
}

export function getModesByFamily(family: string): GameModeDefinition[] {
  return GAME_MODES.filter((m) => m.family === family && isModeEnabled(m.featureFlag));
}

export function getActiveModes(): GameModeDefinition[] {
  return GAME_MODES.filter((m) => m.active && isModeEnabled(m.featureFlag));
}
