import { QuestionTemplate } from "./types";

export const FACTORY_TEMPLATES: QuestionTemplate[] = [
  // --- GEOGRAPHY ---
  {
    templateId: "geo-capital-direct",
    predicate: "capital",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quelle est la capitale de {subject} ?",
    templateExplanation: "{object} est la capitale officielle de {subject}.",
    category: "Geography",
    subcategory: "Capitals",
    difficultyEstimate: "easy",
  },
  {
    templateId: "geo-capital-reverse",
    predicate: "capital_of",
    direction: "object_to_subject",
    languageCode: "fr",
    templatePrompt: "{subject} est la capitale de quel pays ?",
    templateExplanation: "{subject} est la capitale et le centre institutionnel de {object}.",
    category: "Geography",
    subcategory: "Capitals",
    difficultyEstimate: "medium",
  },
  {
    templateId: "geo-continent",
    predicate: "continent",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Sur quel continent se situe {subject} ?",
    templateExplanation: "{subject} est un territoire situé sur le continent {object}.",
    category: "Geography",
    subcategory: "Continents",
    difficultyEstimate: "easy",
  },
  {
    templateId: "geo-currency",
    predicate: "currency",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quelle est la monnaie officielle de {subject} ?",
    templateExplanation: "{object} est l'unité monétaire officielle en circulation en {subject}.",
    category: "Geography",
    subcategory: "Currencies",
    difficultyEstimate: "medium",
  },
  {
    templateId: "geo-highest-point",
    predicate: "highest_point",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel est le point culminant de {subject} ?",
    templateExplanation: "{object} constitue le sommet le plus élevé de {subject}.",
    category: "Geography",
    subcategory: "Mountains",
    difficultyEstimate: "hard",
  },

  // --- ART ---
  {
    templateId: "art-painter",
    predicate: "created_by_painter",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel artiste a peint le célèbre chef-d'œuvre « {subject} » ?",
    templateExplanation: "L'œuvre « {subject} » a été réalisée par le peintre {object}.",
    category: "Art",
    subcategory: "Painting",
    difficultyEstimate: "easy",
  },
  {
    templateId: "art-sculptor",
    predicate: "created_by_sculptor",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel sculpteur est l'auteur de la célèbre sculpture « {subject} » ?",
    templateExplanation: "La sculpture « {subject} » a été créée par {object}.",
    category: "Art",
    subcategory: "Sculpture",
    difficultyEstimate: "medium",
  },

  // --- LITERATURE ---
  {
    templateId: "lit-author",
    predicate: "authored_by",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel écrivain est l'auteur de l'ouvrage « {subject} » ?",
    templateExplanation: "Le livre « {subject} » est un ouvrage majeur écrit par {object}.",
    category: "Literature",
    subcategory: "Novels",
    difficultyEstimate: "easy",
  },
  {
    templateId: "lit-nationality",
    predicate: "author_nationality",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "De quelle nationalité était l'écrivain {subject} ?",
    templateExplanation: "{subject} était un grand auteur de nationalité {object}.",
    category: "Literature",
    subcategory: "Authors",
    difficultyEstimate: "medium",
  },

  // --- CINEMA ---
  {
    templateId: "cin-director",
    predicate: "directed_by",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel cinéaste a réalisé le film « {subject} » ?",
    templateExplanation: "Le long-métrage « {subject} » a été mis en scène par le réalisateur {object}.",
    category: "Cinema",
    subcategory: "Directors",
    difficultyEstimate: "easy",
  },

  // --- MUSIC ---
  {
    templateId: "mus-composer",
    predicate: "composed_by",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel compositeur est l'auteur de l'œuvre musicale « {subject} » ?",
    templateExplanation: "La composition « {subject} » est l'une des œuvres célèbres de {object}.",
    category: "Music",
    subcategory: "Classical",
    difficultyEstimate: "easy",
  },

  // --- SCIENCE ---
  {
    templateId: "sci-chem-symbol",
    predicate: "chemical_symbol",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel est le symbole chimique de l'élément « {subject} » ?",
    templateExplanation: "Dans la classification périodique des éléments, {subject} a pour symbole chimique {object}.",
    category: "Science",
    subcategory: "Chemistry",
    difficultyEstimate: "medium",
  },
  {
    templateId: "sci-atomic-number",
    predicate: "atomic_number",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel élément chimique a pour numéro atomique {subject} ?",
    templateExplanation: "L'élément chimique possédant le numéro atomique {subject} est {object}.",
    category: "Science",
    subcategory: "Periodic Table",
    difficultyEstimate: "hard",
  },
  {
    templateId: "sci-discovery",
    predicate: "discovered_by",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Quel scientifique a découvert ou formulé « {subject} » ?",
    templateExplanation: "La découverte de « {subject} » est historiquement attribuée à {object}.",
    category: "Science",
    subcategory: "Discoveries",
    difficultyEstimate: "medium",
  },

  // --- NATURE ---
  {
    templateId: "nat-class",
    predicate: "taxonomic_class",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "À quelle classe animale appartient {subject} ?",
    templateExplanation: "{subject} est classé biologiquement parmi les {object}.",
    category: "Nature",
    subcategory: "Zoology",
    difficultyEstimate: "easy",
  },

  // --- HISTORY ---
  {
    templateId: "hist-year",
    predicate: "event_year",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "En quelle année s'est déroulé l'événement historique « {subject} » ?",
    templateExplanation: "L'événement historique « {subject} » a eu lieu en {object}.",
    category: "History",
    subcategory: "Chronology",
    difficultyEstimate: "medium",
  },
  {
    templateId: "hist-monarch-dynasty",
    predicate: "dynasty",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "À quelle dynastie régnante appartenait {subject} ?",
    templateExplanation: "{subject} était un souverain issu de la dynastie des {object}.",
    category: "History",
    subcategory: "Monarchy",
    difficultyEstimate: "medium",
  },

  // --- FOOD & CULTURE ---
  {
    templateId: "food-origin",
    predicate: "origin_country",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "De quel pays est originaire la spécialité culinaire « {subject} » ?",
    templateExplanation: "La spécialité gastronomique « {subject} » trouve son origine traditionnelle en {object}.",
    category: "Food & Culture",
    subcategory: "Gastronomy",
    difficultyEstimate: "easy",
  },

  // --- TECHNOLOGY ---
  {
    templateId: "tech-creator",
    predicate: "tech_creator",
    direction: "subject_to_object",
    languageCode: "fr",
    templatePrompt: "Qui est le créateur ou inventeur principal de « {subject} » ?",
    templateExplanation: "Le développement et la création de « {subject} » ont été menés par {object}.",
    category: "Technology",
    subcategory: "Inventions",
    difficultyEstimate: "medium",
  },
];
