export interface SeedQuestion {
  id: string;
  category: string;
  subcategory?: string;
  prompt: string;
  difficulty: "easy" | "medium" | "hard" | "expert";
  seconds: number;
  explanation: string;
  source: string;
  answers: { id: string; label: string; isCorrect: boolean }[];
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // --- GEOGRAPHY ---
  {
    id: "geo-001",
    category: "Geography",
    subcategory: "World Coastlines",
    prompt: "Which country in the world has the longest total coastline?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Canada has the world's longest coastline at over 202,080 kilometers (125,567 miles).",
    source: "Statistics Canada / World Factbook",
    answers: [
      { id: "a", label: "Canada", isCorrect: true },
      { id: "b", label: "Russia", isCorrect: false },
      { id: "c", label: "Indonesia", isCorrect: false },
      { id: "d", label: "Australia", isCorrect: false },
    ],
  },
  {
    id: "geo-002",
    category: "Geography",
    subcategory: "European Geography",
    prompt: "Which natural maritime strait separates the European continent from Africa?",
    difficulty: "easy",
    seconds: 10,
    explanation: "The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea and separates Spain from Morocco by approximately 14 km at its narrowest point.",
    source: "International Hydrographic Organization",
    answers: [
      { id: "a", label: "Bosphorus Strait", isCorrect: false },
      { id: "b", label: "Strait of Hormuz", isCorrect: false },
      { id: "c", label: "Strait of Gibraltar", isCorrect: true },
      { id: "d", label: "Bering Strait", isCorrect: false },
    ],
  },
  {
    id: "geo-003",
    category: "Geography",
    subcategory: "African Lakes",
    prompt: "What is the largest lake in Africa by surface area?",
    difficulty: "medium",
    seconds: 10,
    explanation: "Lake Victoria covers approximately 68,800 square kilometers, shared by Uganda, Kenya, and Tanzania.",
    source: "UNEP Lake Basin Management",
    answers: [
      { id: "a", label: "Lake Tanganyika", isCorrect: false },
      { id: "b", label: "Lake Victoria", isCorrect: true },
      { id: "c", label: "Lake Malawi", isCorrect: false },
      { id: "d", label: "Lake Chad", isCorrect: false },
    ],
  },
  {
    id: "geo-004",
    category: "Geography",
    subcategory: "Capitals",
    prompt: "What is the official capital city of Australia?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Canberra was selected as the capital in 1908 as a compromise between rival cities Sydney and Melbourne.",
    source: "National Archives of Australia",
    answers: [
      { id: "a", label: "Sydney", isCorrect: false },
      { id: "b", label: "Melbourne", isCorrect: false },
      { id: "c", label: "Canberra", isCorrect: true },
      { id: "d", label: "Brisbane", isCorrect: false },
    ],
  },
  {
    id: "geo-005",
    category: "Geography",
    subcategory: "Mountains",
    prompt: "Which is the highest mountain peak in North America?",
    difficulty: "medium",
    seconds: 10,
    explanation: "Denali (formerly Mount McKinley) in Alaska rises to an elevation of 6,190 meters (20,310 feet) above sea level.",
    source: "US Geological Survey",
    answers: [
      { id: "a", label: "Mount Logan", isCorrect: false },
      { id: "b", label: "Denali", isCorrect: true },
      { id: "c", label: "Mount Rainier", isCorrect: false },
      { id: "d", label: "Mount Whitney", isCorrect: false },
    ],
  },

  // --- HISTORY ---
  {
    id: "hist-001",
    category: "History",
    subcategory: "Ancient Civilizations",
    prompt: "Which pre-Columbian civilization constructed the mountain citadel of Machu Picchu?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Machu Picchu was built by the Inca Empire around 1450 CE under Emperor Pachacuti.",
    source: "UNESCO World Heritage Centre",
    answers: [
      { id: "a", label: "Aztec Empire", isCorrect: false },
      { id: "b", label: "Inca Empire", isCorrect: true },
      { id: "c", label: "Maya Civilization", isCorrect: false },
      { id: "d", label: "Olmec Civilization", isCorrect: false },
    ],
  },
  {
    id: "hist-002",
    category: "History",
    subcategory: "20th Century",
    prompt: "In which year did the Berlin Wall fall, opening the border between East and West Germany?",
    difficulty: "easy",
    seconds: 10,
    explanation: "On November 9, 1989, East German officials announced that citizens were free to cross the border.",
    source: "German Federal Archives",
    answers: [
      { id: "a", label: "1987", isCorrect: false },
      { id: "b", label: "1989", isCorrect: true },
      { id: "c", label: "1991", isCorrect: false },
      { id: "d", label: "1985", isCorrect: false },
    ],
  },
  {
    id: "hist-003",
    category: "History",
    subcategory: "French History",
    prompt: "Which French monarch was nicknamed the 'Sun King' (Le Roi Soleil)?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Louis XIV reigned for 72 years and 110 days from 1643 to 1715, the longest recorded reign of any sovereign monarch in history.",
    source: "Château de Versailles Historical Registry",
    answers: [
      { id: "a", label: "Louis XIV", isCorrect: true },
      { id: "b", label: "Louis XVI", isCorrect: false },
      { id: "c", label: "Henri IV", isCorrect: false },
      { id: "d", label: "François I", isCorrect: false },
    ],
  },
  {
    id: "hist-004",
    category: "History",
    subcategory: "Roman Antiquity",
    prompt: "Who was the first official Emperor of the Roman Empire, ruling from 27 BCE until 14 CE?",
    difficulty: "medium",
    seconds: 10,
    explanation: "Octavian was granted the title Augustus by the Roman Senate in 27 BCE, marking the transition from Republic to Principate.",
    source: "Cambridge Ancient History",
    answers: [
      { id: "a", label: "Julius Caesar", isCorrect: false },
      { id: "b", label: "Augustus", isCorrect: true },
      { id: "c", label: "Nero", isCorrect: false },
      { id: "d", label: "Trajan", isCorrect: false },
    ],
  },
  {
    id: "hist-005",
    category: "History",
    subcategory: "Middle Ages",
    prompt: "In which year did the Battle of Hastings take place, establishing Norman rule in England?",
    difficulty: "medium",
    seconds: 10,
    explanation: "On October 14, 1066, William the Conqueror defeated King Harold Godwinson near Hastings.",
    source: "Bayeux Tapestry / English Heritage",
    answers: [
      { id: "a", label: "1066", isCorrect: true },
      { id: "b", label: "1215", isCorrect: false },
      { id: "c", label: "1415", isCorrect: false },
      { id: "d", label: "987", isCorrect: false },
    ],
  },

  // --- SCIENCE ---
  {
    id: "sci-001",
    category: "Science",
    subcategory: "Chemistry",
    prompt: "Which chemical element on the periodic table is represented by the symbol W?",
    difficulty: "medium",
    seconds: 10,
    explanation: "Tungsten's symbol W comes from its German name 'Wolfram', having the highest melting point of all metallic elements (3,422°C).",
    source: "IUPAC Periodic Table",
    answers: [
      { id: "a", label: "Tungsten", isCorrect: true },
      { id: "b", label: "Tin", isCorrect: false },
      { id: "c", label: "Uranium", isCorrect: false },
      { id: "d", label: "Zirconium", isCorrect: false },
    ],
  },
  {
    id: "sci-002",
    category: "Science",
    subcategory: "Atmosphere",
    prompt: "What is the most abundant gas in Earth's atmosphere by volume?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Nitrogen makes up approximately 78.08% of Earth's atmosphere, followed by oxygen at 20.95% and argon at 0.93%.",
    source: "NASA Earth Observatory",
    answers: [
      { id: "a", label: "Oxygen", isCorrect: false },
      { id: "b", label: "Carbon dioxide", isCorrect: false },
      { id: "c", label: "Nitrogen", isCorrect: true },
      { id: "d", label: "Argon", isCorrect: false },
    ],
  },
  {
    id: "sci-003",
    category: "Science",
    subcategory: "Physics",
    prompt: "What is the approximate speed of light in a vacuum?",
    difficulty: "easy",
    seconds: 10,
    explanation: "The speed of light in vacuum is exactly 299,792,458 meters per second (approximately 300,000 km/s).",
    source: "NIST Physical Constants",
    answers: [
      { id: "a", label: "300,000 km/s", isCorrect: true },
      { id: "b", label: "150,000 km/s", isCorrect: false },
      { id: "c", label: "450,000 km/s", isCorrect: false },
      { id: "d", label: "1,000,000 km/s", isCorrect: false },
    ],
  },
  {
    id: "sci-004",
    category: "Science",
    subcategory: "Biology",
    prompt: "Which organelle is widely known as the power-generator or powerhouse of eukaryotic cells?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Mitochondria generate most of the chemical energy needed to power biochemical reactions in the form of ATP.",
    source: "Cell Biology Compendium",
    answers: [
      { id: "a", label: "Ribosome", isCorrect: false },
      { id: "b", label: "Mitochondria", isCorrect: true },
      { id: "c", label: "Golgi apparatus", isCorrect: false },
      { id: "d", label: "Endoplasmic reticulum", isCorrect: false },
    ],
  },
  {
    id: "sci-005",
    category: "Science",
    subcategory: "Astronomy",
    prompt: "Which planet in our Solar System has the greatest number of confirmed moons (as of 2026)?",
    difficulty: "medium",
    seconds: 10,
    explanation: "Saturn has 146 recognized moons, surpassing Jupiter's 95 confirmed moons.",
    source: "NASA Solar System Exploration / Minor Planet Center",
    answers: [
      { id: "a", label: "Jupiter", isCorrect: false },
      { id: "b", label: "Saturn", isCorrect: true },
      { id: "c", label: "Uranus", isCorrect: false },
      { id: "d", label: "Neptune", isCorrect: false },
    ],
  },

  // --- SPORTS ---
  {
    id: "spo-001",
    category: "Sports",
    subcategory: "Rugby",
    prompt: "How many players per team are on the field in a standard rugby union match?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Rugby union features 15 players per side on the field, whereas rugby league has 13 players.",
    source: "World Rugby Official Regulations",
    answers: [
      { id: "a", label: "13", isCorrect: false },
      { id: "b", label: "14", isCorrect: false },
      { id: "c", label: "15", isCorrect: true },
      { id: "d", label: "11", isCorrect: false },
    ],
  },
  {
    id: "spo-002",
    category: "Sports",
    subcategory: "Football",
    prompt: "Which national team has won the most FIFA Men's World Cup titles (5)?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Brazil won the World Cup in 1958, 1962, 1970, 1994, and 2002.",
    source: "FIFA Official Archives",
    answers: [
      { id: "a", label: "Germany", isCorrect: false },
      { id: "b", label: "Italy", isCorrect: false },
      { id: "c", label: "Argentina", isCorrect: false },
      { id: "d", label: "Brazil", isCorrect: true },
    ],
  },
  {
    id: "spo-003",
    category: "Sports",
    subcategory: "Tennis",
    prompt: "Which Grand Slam tennis tournament is played exclusively on clay courts?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Roland-Garros (the French Open) in Paris is the premier clay court tennis championship.",
    source: "International Tennis Federation",
    answers: [
      { id: "a", label: "Wimbledon", isCorrect: false },
      { id: "b", label: "Roland-Garros", isCorrect: true },
      { id: "c", label: "Australian Open", isCorrect: false },
      { id: "d", label: "US Open", isCorrect: false },
    ],
  },

  // --- CINEMA ---
  {
    id: "cin-001",
    category: "Cinema",
    subcategory: "Directors",
    prompt: "Who directed the critically acclaimed Academy Award-winning film 'Parasite' (2019)?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Bong Joon-ho won Best Picture, Best Director, and Best Original Screenplay for 'Parasite'.",
    source: "Academy of Motion Picture Arts and Sciences",
    answers: [
      { id: "a", label: "Park Chan-wook", isCorrect: false },
      { id: "b", label: "Bong Joon-ho", isCorrect: true },
      { id: "c", label: "Kim Ki-duk", isCorrect: false },
      { id: "d", label: "Lee Chang-dong", isCorrect: false },
    ],
  },
  {
    id: "cin-002",
    category: "Cinema",
    subcategory: "Sci-Fi",
    prompt: "In the 1999 film 'The Matrix', which color pill does Neo take to wake up in the real world?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Morpheus offers Neo the blue pill (remain in ignorance) or the red pill (see the truth). Neo takes the red pill.",
    source: "Warner Bros. Archives",
    answers: [
      { id: "a", label: "Blue pill", isCorrect: false },
      { id: "b", label: "Red pill", isCorrect: true },
      { id: "c", label: "Green pill", isCorrect: false },
      { id: "d", label: "Yellow pill", isCorrect: false },
    ],
  },

  // --- MUSIC ---
  {
    id: "mus-001",
    category: "Music",
    subcategory: "Instruments",
    prompt: "Which type of instruments does a luthier traditionally construct, craft and repair?",
    difficulty: "medium",
    seconds: 10,
    explanation: "A luthier is an artisan who makes and repairs string instruments such as violins, guitars, and cellos.",
    source: "Oxford Music Online",
    answers: [
      { id: "a", label: "Percussion instruments", isCorrect: false },
      { id: "b", label: "Stringed instruments", isCorrect: true },
      { id: "c", label: "Pipe organs", isCorrect: false },
      { id: "d", label: "Woodwind instruments", isCorrect: false },
    ],
  },
  {
    id: "mus-002",
    category: "Music",
    subcategory: "Classical",
    prompt: "Which composer wrote the famous 'Ode to Joy' in his Ninth Symphony while completely deaf?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Ludwig van Beethoven premiered his Ninth Symphony in Vienna in 1824, incorporating Friedrich Schiller's poem 'Ode to Joy'.",
    source: "Beethoven-Haus Bonn",
    answers: [
      { id: "a", label: "Wolfgang Amadeus Mozart", isCorrect: false },
      { id: "b", label: "Ludwig van Beethoven", isCorrect: true },
      { id: "c", label: "Johann Sebastian Bach", isCorrect: false },
      { id: "d", label: "Franz Schubert", isCorrect: false },
    ],
  },

  // --- ART ---
  {
    id: "art-001",
    category: "Art",
    subcategory: "Post-Impressionism",
    prompt: "Which artist painted the famous masterpiece 'The Starry Night' in Saint-Rémy-de-Provence (1889)?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Vincent van Gogh painted 'The Starry Night' from his asylum room in June 1889.",
    source: "Museum of Modern Art (MoMA)",
    answers: [
      { id: "a", label: "Paul Gauguin", isCorrect: false },
      { id: "b", label: "Vincent van Gogh", isCorrect: true },
      { id: "c", label: "Edvard Munch", isCorrect: false },
      { id: "d", label: "Claude Monet", isCorrect: false },
    ],
  },
  {
    id: "art-002",
    category: "Art",
    subcategory: "Sculpture",
    prompt: "Which Italian Renaissance sculptor created the marble statue 'David' (1501–1504)?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Michelangelo Buonarroti sculpted the 5.17-meter masterpiece in Florence.",
    source: "Galleria dell'Accademia Firenze",
    answers: [
      { id: "a", label: "Donatello", isCorrect: false },
      { id: "b", label: "Michelangelo", isCorrect: true },
      { id: "c", label: "Bernini", isCorrect: false },
      { id: "d", label: "Leonardo da Vinci", isCorrect: false },
    ],
  },

  // --- LITERATURE ---
  {
    id: "lit-001",
    category: "Literature",
    subcategory: "Magical Realism",
    prompt: "Who authored the acclaimed novel 'One Hundred Years of Solitude' (Cien años de soledad)?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Colombian author Gabriel García Márquez published the novel in 1967 and won the Nobel Prize in Literature in 1982.",
    source: "Nobel Prize in Literature Archives",
    answers: [
      { id: "a", label: "Gabriel García Márquez", isCorrect: true },
      { id: "b", label: "Jorge Luis Borges", isCorrect: false },
      { id: "c", label: "Mario Vargas Llosa", isCorrect: false },
      { id: "d", label: "Julio Cortázar", isCorrect: false },
    ],
  },
  {
    id: "lit-002",
    category: "Literature",
    subcategory: "French Literature",
    prompt: "Who wrote the epic 19th-century French novel 'Les Misérables'?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Victor Hugo published 'Les Misérables' in 1862 after nearly two decades of work.",
    source: "Maison de Victor Hugo",
    answers: [
      { id: "a", label: "Émile Zola", isCorrect: false },
      { id: "b", label: "Victor Hugo", isCorrect: true },
      { id: "c", label: "Gustave Flaubert", isCorrect: false },
      { id: "d", label: "Alexandre Dumas", isCorrect: false },
    ],
  },

  // --- TECHNOLOGY ---
  {
    id: "tech-001",
    category: "Technology",
    subcategory: "Computer Science",
    prompt: "Who is widely recognized as the world's first computer programmer for writing an algorithm for Babbage's Analytical Engine?",
    difficulty: "medium",
    seconds: 10,
    explanation: "Ada Lovelace published the first algorithm intended to be executed by a machine in 1843.",
    source: "British Library Science Collections",
    answers: [
      { id: "a", label: "Grace Hopper", isCorrect: false },
      { id: "b", label: "Ada Lovelace", isCorrect: true },
      { id: "c", label: "Alan Turing", isCorrect: false },
      { id: "d", label: "Margaret Hamilton", isCorrect: false },
    ],
  },
  {
    id: "tech-002",
    category: "Technology",
    subcategory: "Internet History",
    prompt: "In which year was the World Wide Web created by Tim Berners-Lee at CERN?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN.",
    source: "CERN Document Server",
    answers: [
      { id: "a", label: "1983", isCorrect: false },
      { id: "b", label: "1989", isCorrect: true },
      { id: "c", label: "1995", isCorrect: false },
      { id: "d", label: "1977", isCorrect: false },
    ],
  },

  // --- NATURE ---
  {
    id: "nat-001",
    category: "Nature",
    subcategory: "Marine Life",
    prompt: "What is the largest living animal known to have ever existed on Earth?",
    difficulty: "easy",
    seconds: 10,
    explanation: "The blue whale (Balaenoptera musculus) can reach lengths of up to 30 meters and weigh up to 190 metric tons.",
    source: "Natural History Museum London",
    answers: [
      { id: "a", label: "Colossal Squid", isCorrect: false },
      { id: "b", label: "Blue Whale", isCorrect: true },
      { id: "c", label: "African Elephant", isCorrect: false },
      { id: "d", label: "Sperm Whale", isCorrect: false },
    ],
  },
  {
    id: "nat-002",
    category: "Nature",
    subcategory: "Botany",
    prompt: "Which process do plants use to convert sunlight, carbon dioxide, and water into glucose and oxygen?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Photosynthesis occurs inside chloroplasts using the green pigment chlorophyll.",
    source: "Royal Botanic Gardens Kew",
    answers: [
      { id: "a", label: "Cellular respiration", isCorrect: false },
      { id: "b", label: "Photosynthesis", isCorrect: true },
      { id: "c", label: "Fermentation", isCorrect: false },
      { id: "d", label: "Osmosis", isCorrect: false },
    ],
  },

  // --- POLITICS & SOCIETY ---
  {
    id: "soc-001",
    category: "Politics & Society",
    subcategory: "International Organizations",
    prompt: "In which European city is the primary headquarters of the International Court of Justice (ICJ) located?",
    difficulty: "medium",
    seconds: 10,
    explanation: "The International Court of Justice is seated at the Peace Palace in The Hague, Netherlands.",
    source: "United Nations Treaty Collection",
    answers: [
      { id: "a", label: "Geneva", isCorrect: false },
      { id: "b", label: "The Hague", isCorrect: true },
      { id: "c", label: "Brussels", isCorrect: false },
      { id: "d", label: "Vienna", isCorrect: false },
    ],
  },

  // --- FOOD & CULTURE ---
  {
    id: "food-001",
    category: "Food & Culture",
    subcategory: "Spices",
    prompt: "Which expensive spice is derived from the dried stigmas of the Crocus sativus flower?",
    difficulty: "easy",
    seconds: 10,
    explanation: "Saffron is harvested by hand from crocus stigmas, requiring up to 75,000 flowers to produce a single pound.",
    source: "Food and Agriculture Organization (FAO)",
    answers: [
      { id: "a", label: "Cardamom", isCorrect: false },
      { id: "b", label: "Saffron", isCorrect: true },
      { id: "c", label: "Vanilla", isCorrect: false },
      { id: "d", label: "Turmeric", isCorrect: false },
    ],
  },
];
