/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MatchResultRouteImport } from './routes/match-result'
import { Route as MatchReviewRouteImport } from './routes/match-review'
import { Route as MatchmakingRouteImport } from './routes/matchmaking'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ResultRouteImport } from './routes/result'
import { Route as TrainRouteImport } from './routes/train'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as DevMultiplayerRouteImport } from './routes/dev/multiplayer'
import { Route as ModesModeSlugRouteImport } from './routes/modes/$modeSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchResultRoute = MatchResultRouteImport.update({
  id: '/match-result',
  path: '/match-result',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchReviewRoute = MatchReviewRouteImport.update({
  id: '/match-review',
  path: '/match-review',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingRoute = MatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMultiplayerRoute = DevMultiplayerRouteImport.update({
  id: '/dev/multiplayer',
  path: '/dev/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesModeSlugRoute = ModesModeSlugRouteImport.update({
  id: '/modes/$modeSlug',
  path: '/modes/$modeSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battles': typeof BattlesRoute
  '/daily': typeof DailyRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leagues': typeof LeaguesRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/match-result': typeof MatchResultRoute
  '/match-review': typeof MatchReviewRoute
  '/matchmaking': typeof MatchmakingRoute
  '/notifications': typeof NotificationsRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/rankings': typeof RankingsRoute
  '/result': typeof ResultRoute
  '/train': typeof TrainRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/dev/multiplayer': typeof DevMultiplayerRoute
  '/modes/$modeSlug': typeof ModesModeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battles': typeof BattlesRoute
  '/daily': typeof DailyRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leagues': typeof LeaguesRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/match-result': typeof MatchResultRoute
  '/match-review': typeof MatchReviewRoute
  '/matchmaking': typeof MatchmakingRoute
  '/notifications': typeof NotificationsRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/rankings': typeof RankingsRoute
  '/result': typeof ResultRoute
  '/train': typeof TrainRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/dev/multiplayer': typeof DevMultiplayerRoute
  '/modes/$modeSlug': typeof ModesModeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battles': typeof BattlesRoute
  '/daily': typeof DailyRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leagues': typeof LeaguesRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/match-result': typeof MatchResultRoute
  '/match-review': typeof MatchReviewRoute
  '/matchmaking': typeof MatchmakingRoute
  '/notifications': typeof NotificationsRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/rankings': typeof RankingsRoute
  '/result': typeof ResultRoute
  '/train': typeof TrainRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/dev/multiplayer': typeof DevMultiplayerRoute
  '/modes/$modeSlug': typeof ModesModeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battles'
    | '/daily'
    | '/friends'
    | '/home'
    | '/leagues'
    | '/live'
    | '/match'
    | '/match-result'
    | '/match-review'
    | '/matchmaking'
    | '/notifications'
    | '/play'
    | '/profile'
    | '/quiz'
    | '/rankings'
    | '/result'
    | '/train'
    | '/admin/questions'
    | '/dev/multiplayer'
    | '/modes/$modeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battles'
    | '/daily'
    | '/friends'
    | '/home'
    | '/leagues'
    | '/live'
    | '/match'
    | '/match-result'
    | '/match-review'
    | '/matchmaking'
    | '/notifications'
    | '/play'
    | '/profile'
    | '/quiz'
    | '/rankings'
    | '/result'
    | '/train'
    | '/admin/questions'
    | '/dev/multiplayer'
    | '/modes/$modeSlug'
  id:
    | '__root__'
    | '/'
    | '/battles'
    | '/daily'
    | '/friends'
    | '/home'
    | '/leagues'
    | '/live'
    | '/match'
    | '/match-result'
    | '/match-review'
    | '/matchmaking'
    | '/notifications'
    | '/play'
    | '/profile'
    | '/quiz'
    | '/rankings'
    | '/result'
    | '/train'
    | '/admin/questions'
    | '/dev/multiplayer'
    | '/modes/$modeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattlesRoute: typeof BattlesRoute
  DailyRoute: typeof DailyRoute
  FriendsRoute: typeof FriendsRoute
  HomeRoute: typeof HomeRoute
  LeaguesRoute: typeof LeaguesRoute
  LiveRoute: typeof LiveRoute
  MatchRoute: typeof MatchRoute
  MatchResultRoute: typeof MatchResultRoute
  MatchReviewRoute: typeof MatchReviewRoute
  MatchmakingRoute: typeof MatchmakingRoute
  NotificationsRoute: typeof NotificationsRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  RankingsRoute: typeof RankingsRoute
  ResultRoute: typeof ResultRoute
  TrainRoute: typeof TrainRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  DevMultiplayerRoute: typeof DevMultiplayerRoute
  ModesModeSlugRoute: typeof ModesModeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-result': {
      id: '/match-result'
      path: '/match-result'
      fullPath: '/match-result'
      preLoaderRoute: typeof MatchResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-review': {
      id: '/match-review'
      path: '/match-review'
      fullPath: '/match-review'
      preLoaderRoute: typeof MatchReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking': {
      id: '/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof MatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/multiplayer': {
      id: '/dev/multiplayer'
      path: '/dev/multiplayer'
      fullPath: '/dev/multiplayer'
      preLoaderRoute: typeof DevMultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/$modeSlug': {
      id: '/modes/$modeSlug'
      path: '/modes/$modeSlug'
      fullPath: '/modes/$modeSlug'
      preLoaderRoute: typeof ModesModeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattlesRoute: BattlesRoute,
  DailyRoute: DailyRoute,
  FriendsRoute: FriendsRoute,
  HomeRoute: HomeRoute,
  LeaguesRoute: LeaguesRoute,
  LiveRoute: LiveRoute,
  MatchRoute: MatchRoute,
  MatchResultRoute: MatchResultRoute,
  MatchReviewRoute: MatchReviewRoute,
  MatchmakingRoute: MatchmakingRoute,
  NotificationsRoute: NotificationsRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  RankingsRoute: RankingsRoute,
  ResultRoute: ResultRoute,
  TrainRoute: TrainRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  DevMultiplayerRoute: DevMultiplayerRoute,
  ModesModeSlugRoute: ModesModeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
