/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MatchResultRouteImport } from './routes/match-result'
import { Route as MatchmakingRouteImport } from './routes/matchmaking'
import { Route as PlayRouteImport } from './routes/play'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ResultRouteImport } from './routes/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchResultRoute = MatchResultRouteImport.update({
  id: '/match-result',
  path: '/match-result',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingRoute = MatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/leagues': typeof LeaguesRoute
  '/match': typeof MatchRoute
  '/match-result': typeof MatchResultRoute
  '/matchmaking': typeof MatchmakingRoute
  '/play': typeof PlayRoute
  '/quiz': typeof QuizRoute
  '/rankings': typeof RankingsRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/leagues': typeof LeaguesRoute
  '/match': typeof MatchRoute
  '/match-result': typeof MatchResultRoute
  '/matchmaking': typeof MatchmakingRoute
  '/play': typeof PlayRoute
  '/quiz': typeof QuizRoute
  '/rankings': typeof RankingsRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/leagues': typeof LeaguesRoute
  '/match': typeof MatchRoute
  '/match-result': typeof MatchResultRoute
  '/matchmaking': typeof MatchmakingRoute
  '/play': typeof PlayRoute
  '/quiz': typeof QuizRoute
  '/rankings': typeof RankingsRoute
  '/result': typeof ResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/leagues'
    | '/match'
    | '/match-result'
    | '/matchmaking'
    | '/play'
    | '/quiz'
    | '/rankings'
    | '/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/leagues'
    | '/match'
    | '/match-result'
    | '/matchmaking'
    | '/play'
    | '/quiz'
    | '/rankings'
    | '/result'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/leagues'
    | '/match'
    | '/match-result'
    | '/matchmaking'
    | '/play'
    | '/quiz'
    | '/rankings'
    | '/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LeaguesRoute: typeof LeaguesRoute
  MatchRoute: typeof MatchRoute
  MatchResultRoute: typeof MatchResultRoute
  MatchmakingRoute: typeof MatchmakingRoute
  PlayRoute: typeof PlayRoute
  QuizRoute: typeof QuizRoute
  RankingsRoute: typeof RankingsRoute
  ResultRoute: typeof ResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-result': {
      id: '/match-result'
      path: '/match-result'
      fullPath: '/match-result'
      preLoaderRoute: typeof MatchResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking': {
      id: '/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof MatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LeaguesRoute: LeaguesRoute,
  MatchRoute: MatchRoute,
  MatchResultRoute: MatchResultRoute,
  MatchmakingRoute: MatchmakingRoute,
  PlayRoute: PlayRoute,
  QuizRoute: QuizRoute,
  RankingsRoute: RankingsRoute,
  ResultRoute: ResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
